name: you
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter

  assets_audio_player: ^3.0.3+6
  
  auto_route: ^2.2.0

  bot_toast: ^4.0.1

  cached_network_image: ^3.0.0
  
  clean_nepali_calendar:
    git:
      url: git://github.com/stha-ums/clean_nepali_calendar.git
      ref: dev-new


  cupertino_icons: ^1.0.3

  dartz: ^0.10.0-nullsafety.1

  equatable: ^2.0.3

  flutter_bloc: ^7.1.0

  get_it: ^7.1.3

  google_fonts: ^2.1.0

  flutter_compass: ^0.6.1

  flare_flutter: ^3.0.1

  flutter_hooks: ^0.17.0

  fluttericon: ^2.0.0

  flutter_secure_storage: ^4.2.0

  flutter_svg: ^0.22.0

  flutter_widget_from_html: ^0.6.1

  flutter_login_facebook: ^1.1.0

  freezed_annotation: ^0.14.2

  google_sign_in: ^5.0.7

  haversine_distance: ^1.2.1

  image_picker: ^0.8.3+3

  intl: ^0.17.0

  location: ^4.3.0

  logging: ^1.0.1

  nepali_date_picker: ^5.1.0

  nepali_utils: ^3.0.1

  qr_code_scanner: ^0.5.1

  qr_flutter: ^4.0.0

  reorderables: ^0.4.1

  sensors: ^2.0.3
  
  share: ^2.0.4

  shared_preferences: ^2.0.6

  shimmer: ^2.0.0

  syncfusion_flutter_charts: ^19.2.47

  syncfusion_flutter_datagrid: ^19.2.47-beta

  timeago: ^3.0.2

  timelines: ^0.1.0

  url_strategy: ^0.2.0

  url_launcher: ^6.0.9

  webview_flutter: ^2.0.9

  youtube_player_flutter: ^8.0.0
  animated_splash_screen: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.3
  freezed: ^0.14.2
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/compass/
    - assets/Archive/
    - assets/data/
    - assets/images/
    - assets/flags/





